import type { NextPage } from "next";
import Head from "next/head";
import { FormEvent, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [inputNameValue, setInputNameValue] = useState("");
  const [inputEmailValue, setInputEmailValue] = useState("");
  const [inputSubjectValue, setInputSubjectValue] = useState("");
  const [inputMessageValue, setInputMessageValue] = useState("");

  function onSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();

    if (!inputEmailValue || !inputNameValue) {
      return;
    }

    const data = {
      name: inputNameValue,
      email: inputEmailValue,
      subject: inputSubjectValue,
      message: inputMessageValue,
    };

    fetch("/api/mail/send", {
      method: "POST",
      body: JSON.stringify(data),
      headers: {
        "Content-type": "application/json",
      },
    })
      .then((r) => r.json())
      .then((r) => console.log(r))
      .catch((err) => console.log(err));
  }

  return (
    <div>
      <Head>
        <title>Send Mail Solution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form onSubmit={(e) => onSubmit(e)}>
          <input
            type="tel"
            name="name"
            id="name"
            value={inputNameValue}
            onChange={(e) => setInputNameValue(e.target.value)}
          />
          <input
            type="email"
            name="email"
            id="email"
            value={inputEmailValue}
            onChange={(e) => setInputEmailValue(e.target.value)}
          />

          <input
            type="subject"
            name="subject"
            id="subject"
            value={inputSubjectValue}
            onChange={(e) => setInputSubjectValue(e.target.value)}
          />

          <textarea
            name="message"
            onChange={(e) => setInputMessageValue(e.target.value)}
            value={inputMessageValue}
            cols={30}
            rows={10}
            maxLength={120}
          ></textarea>
          <button type="submit">ENVIAR</button>
        </form>
      </main>
    </div>
  );
};

export default Home;
