import type { NextPage } from "next";
import Head from "next/head";
import { FormEvent, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [inputNameValue, setInputNameValue] = useState("");
  const [inputEmailValue, setInputEmailValue] = useState("");

  function onSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();

    if (!inputEmailValue || !inputNameValue) {
      return;
    }

    const data = {
      name: inputNameValue,
      email: inputEmailValue,
    };

    console.log(data);
  }

  return (
    <div>
      <Head>
        <title>Send Mail Solution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form onSubmit={(e) => onSubmit(e)}>
          <input
            type="tel"
            name="name"
            id="name"
            value={inputNameValue}
            onChange={(e) => setInputNameValue(e.target.value)}
          />
          <input
            type="email"
            name="email"
            id="email"
            value={inputEmailValue}
            onChange={(e) => setInputEmailValue(e.target.value)}
          />
          <button type="submit">ENVIAR</button>
        </form>
      </main>
    </div>
  );
};

export default Home;
